config/routes.rb
Rails.application.routes.draw do

  root "organizations#home"

  resources :tech_stacks, only: [:create, :new, :destroy]

  resources :organizations do
    get :logo, on: :member

    collection do
      get :home
    end
  end

  resources :claim_organizations

  get '/about' => 'home#about'

  resources :events

  resources :meetups, only: [:create, :new, :destroy]

  resources :users

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

  resources :news_searches
  
  resources :news, only: [:index]

  get "admin/users" => "admin#users"

end

app/models/event.rb
class Event < ActiveRecord::Base # :nodoc:
  belongs_to :meetup

  validates :title, uniqueness: { scope: :time }

  def start_time
    self.time
  end
end

app/models/meetup.rb
class Meetup < ActiveRecord::Base
  has_many :events, dependent: :destroy

  validates :title, presence: true, uniqueness: { message: "This Meetup is already in your list." }

  def total_events
    conn = Faraday.new(url: 'https://api.meetup.com') do |faraday|
      faraday.request  :url_encoded             # form-encode POST params
      faraday.response :logger                  # log requests to STDOUT
      faraday.adapter  Faraday.default_adapter  # make requests with Net::HTTP
    end

    response = conn.get url
    JSON.parse(response.body)
  end

  def seed_events(range)
    total_events.each do |event|
      event_time = event["time"]/1000

      if Time.at(event_time) < range.to_time
        Event.create(title: event["name"], url: event["link"], description: event["description"], group_name: event["group"]["name"], time: Time.at(event_time).localtime, meetup_id: id)
      end
    end
  end
end

app/models/news_search.rb
class NewsSearch < ActiveRecord::Base
end

app/models/organization.rb
class Organization < ActiveRecord::Base
  require 'carrierwave/orm/activerecord'

  mount_uploaders :images, ImageUploader

  has_many :tech_taggings, dependent: :destroy
  has_many :tech_stacks, through: :tech_taggings

  belongs_to :user

  has_many :pending_requests
  has_many :pending_mangers, through: :pending_requests, source: :user

  mount_uploader :logo, LogoUploader
end

app/models/pending_request.rb
class PendingRequest < ActiveRecord::Base
  belongs_to :user
  belongs_to :organization
end

app/models/tech_stack.rb
class TechStack < ActiveRecord::Base
  has_many :tech_taggings, dependent: :destroy
  has_many :tagged_organizations, through: :tech_taggings, source: :organization

  validates :name, presence: true, uniqueness: { message: "This technology already exists" }
end

app/models/tech_tagging.rb
class TechTagging < ActiveRecord::Base
  belongs_to :organization
  belongs_to :tech_stack
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  belongs_to :organization

  has_many :pending_requests
  has_many :pending_organization, through: :pending_requests, source: :organization

  validates :first_name, presence: true

  validates :last_name, presence: true

  VALID_EMAIL_REGEX = /\A([\w+\-]\.?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :email, uniqueness: true, presence: true, format: VALID_EMAIL_REGEX
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
end

app/controllers/claim_organizations_controller.rb
class ClaimOrganizationsController < ApplicationController

  def create
    @pending = PendingRequest.new
    @pending.organization = Organization.find params[:organization]
    @pending.user = current_user
    @pending.save
    redirect_to claim_organizations_path
  end

  def edit
    pending = PendingRequest.find params[:id]
    pending_org      = pending.organization
    pending_org.user = pending.user
    if pending_org.save
      redirect_to claim_organizations_path, notice: "Saved"
    else
      redirect_to claim_organizations_path,notice: "Not saved"
    end
    pending.destroy
  end

  def destroy
    pending = PendingRequest.find params[:id]
    pending.destroy
    redirect_to claim_organizations_path
  end

  def index
    redirect_to users_path
  end

  def new
    @pending = PendingRequest.new
    @pending.organization = Organization.find params[:organization]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def about
  end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  OpenSSL::SSL::VERIFY_PEER = OpenSSL::SSL::VERIFY_NONE

  def index
    string_search_terms
    if @terms
      page = params[:page] || 1
      @news = GoogleCustomSearchApi.search(@terms, page: page)
    end
  end

  def string_search_terms
    @terms = ""
    NewsSearch.all.each do |term|
      @terms += " #{term.search_term}"
    end
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/claim_organizations_helper.rb
module ClaimOrganizationsHelper
end

app/helpers/events_helper.rb
module EventsHelper

  def event_objects
    url = "/HackerNestVan/events?photo-host=public&page=20&sig_id=204710864&sig=bd79ac9a7272dfe2a5a40a8a956b27ea0e1fdb85"

    conn = Faraday.new(url: 'https://api.meetup.com') do |faraday|
      faraday.request  :url_encoded             # form-encode POST params
      faraday.response :logger                  # log requests to STDOUT
      faraday.adapter  Faraday.default_adapter  # make requests with Net::HTTP
    end

    ## GET ##

    response = conn.get url     # GET http://sushi.com/nigiri/sake.json
    total_events = JSON.parse(response.body)

    puts total_events
    # method returns an array of JSON parsed events
  end

  def create_event_objects
    event_objects.each do |event|
      Event.create(title: event.name, url: event.link, description: event.description, group_name: event.group.name, time: event.time)
    end
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/meetups_helper.rb
module MeetupsHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tech_stacks_helper.rb
module TechStacksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/claim_organizations/_index.html.erb
<h3>Pending Claim Requests</h3>

<table class="table">
  <thead>
    <th>First Name</th>
    <th>Last Name</th>
    <th>Email</th>
    <th>Organization</th>
    <th>Actions</th>
  </thead>

  <tbody>
    <% @pendings.each do |pending_user| %>
      <tr>
        <td><%= pending_user.user.first_name %></td>
        <td><%= pending_user.user.last_name %></td>
        <td><%= pending_user.user.email %></td>
        <td><%= pending_user.organization.name %></td>
        <td><%= link_to "Accept",  edit_claim_organization_path(pending_user)%> | <%= link_to "Reject", claim_organization_path(pending_user), method: :delete, data: {confirm:"Are you sure holmes?"} %></td>
      </tr>
    <% end %>
</tbody>
</table>

app/views/claim_organizations/index.html.erb
<table class="table">
  <thead>
    <th>First Name</th>
    <th>Last Name</th>
    <th>Email</th>
    <th>Organization</th>
    <th>Actions</th>
  </thead>

  <tbody>
    <% @pendings.each do |pending_user| %>
      <tr>
        <td><%= pending_user.user.first_name %></td>
        <td><%= pending_user.user.last_name %></td>
        <td><%= pending_user.user.email %></td>
        <td><%= pending_user.organization.name %></td>
        <td><%= link_to "Accept",  edit_claim_organization_path(pending_user)%> | <%= link_to "Reject", claim_organization_path(pending_user), method: :delete, data: {confirm:"Are you sure holmes?"} %></td>
      </tr>
    <% end %>
</tbody>
</table>

app/views/claim_organizations/new.html.erb
<h1>Hello <%= current_user.first_name if user_signed_in? %></h1>
<p>You are about to submit a request to the organization <%= @pending.organization.name %></p>

<%=
  link_to_if(!(user_signed_in?), "Login", { controller: "sessions", action: "new" }) do
    link_to "Continue", claim_organizations_path({organization: @pending.organization}), method: :post
  end
%> |
<%= link_to "Don't Continue", organization_path(@pending.organization) %>