config/routes.rb
Rails.application.routes.draw do

  root "organizations#home"

  resources :tech_stacks, only: [:create, :new, :destroy]

  resources :organizations do
    get :logo, on: :member

    collection do
      get :home
    end
  end

  resources :claim_organizations

  get '/about' => 'home#about'

  resources :events

  resources :meetups, only: [:create, :new, :destroy]

  resources :users

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

  resources :news_searches
  
  resources :news, only: [:index]

  get "admin/users" => "admin#users"

end

app/models/event.rb
class Event < ActiveRecord::Base # :nodoc:
  belongs_to :meetup

  validates :title, uniqueness: { scope: :time }

  def start_time
    self.time
  end
end

app/models/meetup.rb
class Meetup < ActiveRecord::Base
  has_many :events, dependent: :destroy

  validates :title, presence: true, uniqueness: { message: "This Meetup is already in your list." }

  def total_events
    conn = Faraday.new(url: 'https://api.meetup.com') do |faraday|
      faraday.request  :url_encoded             # form-encode POST params
      faraday.response :logger                  # log requests to STDOUT
      faraday.adapter  Faraday.default_adapter  # make requests with Net::HTTP
    end

    response = conn.get url
    JSON.parse(response.body)
  end

  def seed_events(range)
    total_events.each do |event|
      event_time = event["time"]/1000

      if Time.at(event_time) < range.to_time
        Event.create(title: event["name"], url: event["link"], description: event["description"], group_name: event["group"]["name"], time: Time.at(event_time).localtime, meetup_id: id)
      end
    end
  end
end

app/models/news_search.rb
class NewsSearch < ActiveRecord::Base
end

app/models/organization.rb
class Organization < ActiveRecord::Base
  require 'carrierwave/orm/activerecord'

  mount_uploaders :images, ImageUploader

  has_many :tech_taggings, dependent: :destroy
  has_many :tech_stacks, through: :tech_taggings

  belongs_to :user

  has_many :pending_requests
  has_many :pending_mangers, through: :pending_requests, source: :user

  mount_uploader :logo, LogoUploader
end

app/models/pending_request.rb
class PendingRequest < ActiveRecord::Base
  belongs_to :user
  belongs_to :organization
end

app/models/tech_stack.rb
class TechStack < ActiveRecord::Base
  has_many :tech_taggings, dependent: :destroy
  has_many :tagged_organizations, through: :tech_taggings, source: :organization

  validates :name, presence: true, uniqueness: { message: "This technology already exists" }
end

app/models/tech_tagging.rb
class TechTagging < ActiveRecord::Base
  belongs_to :organization
  belongs_to :tech_stack
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  belongs_to :organization

  has_many :pending_requests
  has_many :pending_organization, through: :pending_requests, source: :organization

  validates :first_name, presence: true

  validates :last_name, presence: true

  VALID_EMAIL_REGEX = /\A([\w+\-]\.?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :email, uniqueness: true, presence: true, format: VALID_EMAIL_REGEX
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def about
  end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  OpenSSL::SSL::VERIFY_PEER = OpenSSL::SSL::VERIFY_NONE

  def index
    string_search_terms
    if @terms
      page = params[:page] || 1
      @news = GoogleCustomSearchApi.search(@terms, page: page)
    end
  end

  def string_search_terms
    @terms = ""
    NewsSearch.all.each do |term|
      @terms += " #{term.search_term}"
    end
  end
end

app/controllers/tech_stacks_controller.rb
class TechStacksController < ApplicationController
  before_action :authenticate_admin!, only:[:create, :destroy]

  def index
    @tech_stacks = TechStack.all
    respond_to do |format|
      format.json { render json: @tech_stacks.to_json }
    end
  end

  def create
    tech_stack_params = params.require(:tech_stack).permit(:name)
    @tech_stack = TechStack.new(tech_stack_params)

    respond_to do |format|
      if @tech_stack.save
        format.js { render :create_success }
      else
        format.js { render :create_failure }
      end
    end
  end

  def new
    @tech_stack = TechStack.new
    render :new
  end

  def destroy
    @tech_stack = TechStack.find params[:id]
    @tech_stack.destroy
    respond_to do |format|
      format.js { render :delete_success }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :user_params, only: [:edit, :update, :destroy]
  before_action :authenticate_admin!, only: [:index]

  def index
    @users = User.all
    @pendings = PendingRequest.all
  end


  def new
    @user = User.new
  end

  def create
    @user = User.new(params.require(:user).permit([:first_name, :last_name, :email, :password, :password_confirmation]))

    if @user.save
      sign_in(@user)
      redirect_to root_path, notice: "Account Created!"
    else
      render :new, notice: "Account not created"
    end
  end

  def edit
  end

  def update
    if @user.update(params.require(:user).permit([:first_name, :last_name, :email, :password, :password_confirmation]))
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to root_path
  end

  private

  def user_params
    @user = User.find params[:id]
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper

  def event_objects
    url = "/HackerNestVan/events?photo-host=public&page=20&sig_id=204710864&sig=bd79ac9a7272dfe2a5a40a8a956b27ea0e1fdb85"

    conn = Faraday.new(url: 'https://api.meetup.com') do |faraday|
      faraday.request  :url_encoded             # form-encode POST params
      faraday.response :logger                  # log requests to STDOUT
      faraday.adapter  Faraday.default_adapter  # make requests with Net::HTTP
    end

    ## GET ##

    response = conn.get url     # GET http://sushi.com/nigiri/sake.json
    total_events = JSON.parse(response.body)

    puts total_events
    # method returns an array of JSON parsed events
  end

  def create_event_objects
    event_objects.each do |event|
      Event.create(title: event.name, url: event.link, description: event.description, group_name: event.group.name, time: event.time)
    end
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/meetups_helper.rb
module MeetupsHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/news_searches_helper.rb
module NewsSearchesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tech_stacks_helper.rb
module TechStacksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/tech_stacks/_form.html.erb
<%= simple_form_for tech_stack, remote: true do |f| %>
<%= f.input :name, label: false, placeholder: "Name", wrapper_html: {class: "form-group"}, input_html: {class: "form-control"}  %>
<%= f.submit data: {disable_with: "submitting..."}, class: "btn btn-primary" %>
<% end %>

app/views/tech_stacks/_tech_stack.html.erb
<tr id="<%= dom_id(tech_stack) %>" style="width: 300">
  <td>
    <%= tech_stack.name %>
  </td>
  <td>
    <%= link_to "Remove", tech_stack_path(tech_stack),
                          data: {confirm: "Are you sure?"},
                          method: :delete,
                          remote: true %>
  </td>
</tr>

app/views/tech_stacks/create_failure.js.erb
$("#tech_stack_form").html("<%= j render '/tech_stacks/form', tech_stack: @tech_stack %>");

app/views/tech_stacks/create_success.js.erb
$("#tbody_tech_stacks").prepend("<%= j render '/tech_stacks/tech_stack', tech_stack: @tech_stack, style: 'display: none' %>");
$("#tech_stack_form").html("<%= j render '/tech_stacks/form', tech_stack: TechStack.new %>");
$("#<%= dom_id(@tech_stack) %>").slideDown(1000);

app/views/tech_stacks/delete_success.js.erb
$("#<%= dom_id(@tech_stack) %>").fadeOut(1000, function(){
  $(this).remove();
});

app/views/tech_stacks/new.html.erb
<h1>Technologies</h1>
<div id="tech_stack_form container">
  <%= render "/tech_stacks/form", tech_stack: @tech_stack %>
</div>
<div class="table-responsive">
  <table class="table">
    <thead>
      <tr>
        <th>
          Technology Name
        </th>
        <th>
          Action
        </th>
      </tr>
    </thead>
    <tbody id="tbody_tech_stacks">
      <% TechStack.all.each do |tech| %>
      <%= render "/tech_stacks/tech_stack", tech_stack: tech %>
      <% end %>
    </tbody>
  </table>
</div>