config/routes.rb
Rails.application.routes.draw do

  root "organizations#home"

  resources :tech_stacks, only: [:create, :new, :destroy]

  resources :organizations do
    get :logo, on: :member

    collection do
      get :home
    end
  end

  resources :claim_organizations

  get '/about' => 'home#about'

  resources :events

  resources :meetups, only: [:create, :new, :destroy]

  resources :users

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

  resources :news_searches
  
  resources :news, only: [:index]

  get "admin/users" => "admin#users"

end

app/models/event.rb
class Event < ActiveRecord::Base # :nodoc:
  belongs_to :meetup

  validates :title, uniqueness: { scope: :time }

  def start_time
    self.time
  end
end

app/models/meetup.rb
class Meetup < ActiveRecord::Base
  has_many :events, dependent: :destroy

  validates :title, presence: true, uniqueness: { message: "This Meetup is already in your list." }

  def total_events
    conn = Faraday.new(url: 'https://api.meetup.com') do |faraday|
      faraday.request  :url_encoded             # form-encode POST params
      faraday.response :logger                  # log requests to STDOUT
      faraday.adapter  Faraday.default_adapter  # make requests with Net::HTTP
    end

    response = conn.get url
    JSON.parse(response.body)
  end

  def seed_events(range)
    total_events.each do |event|
      event_time = event["time"]/1000

      if Time.at(event_time) < range.to_time
        Event.create(title: event["name"], url: event["link"], description: event["description"], group_name: event["group"]["name"], time: Time.at(event_time).localtime, meetup_id: id)
      end
    end
  end
end

app/models/news_search.rb
class NewsSearch < ActiveRecord::Base
end

app/models/organization.rb
class Organization < ActiveRecord::Base
  require 'carrierwave/orm/activerecord'

  mount_uploaders :images, ImageUploader

  has_many :tech_taggings, dependent: :destroy
  has_many :tech_stacks, through: :tech_taggings

  belongs_to :user

  has_many :pending_requests
  has_many :pending_mangers, through: :pending_requests, source: :user

  mount_uploader :logo, LogoUploader
end

app/models/pending_request.rb
class PendingRequest < ActiveRecord::Base
  belongs_to :user
  belongs_to :organization
end

app/models/tech_stack.rb
class TechStack < ActiveRecord::Base
  has_many :tech_taggings, dependent: :destroy
  has_many :tagged_organizations, through: :tech_taggings, source: :organization

  validates :name, presence: true, uniqueness: { message: "This technology already exists" }
end

app/models/tech_tagging.rb
class TechTagging < ActiveRecord::Base
  belongs_to :organization
  belongs_to :tech_stack
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  belongs_to :organization

  has_many :pending_requests
  has_many :pending_organization, through: :pending_requests, source: :organization

  validates :first_name, presence: true

  validates :last_name, presence: true

  VALID_EMAIL_REGEX = /\A([\w+\-]\.?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :email, uniqueness: true, presence: true, format: VALID_EMAIL_REGEX
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def about
  end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  OpenSSL::SSL::VERIFY_PEER = OpenSSL::SSL::VERIFY_NONE

  def index
    string_search_terms
    if @terms
      page = params[:page] || 1
      @news = GoogleCustomSearchApi.search(@terms, page: page)
    end
  end

  def string_search_terms
    @terms = ""
    NewsSearch.all.each do |term|
      @terms += " #{term.search_term}"
    end
  end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  before_action :authenticate_user!, only:[:new, :create, :edit, :update, :destroy]

  def new
    @organization = Organization.new
  end

  def home
    @addresses = Organization.all.map { |o| o.address }
    all_tech_stacks
    search = params[:search]

    @organizations = Organization.where(published: true)

    respond_to do |format|
      format.html { render }
      format.json { render json: @organizations.to_json }
      # format.js { render :list_listings }
      # format.js { render :create_map }
    end
  end

  def index
    @organizations = Organization.all
    respond_to do |format|
      format.html { render }
      format.json { render json: @organizations.to_json }
    end
  end

  def create
    @organization = Organization.new(organization_params)
    if @organization.save
      redirect_to organization_path(@organization)
    else
      render :new
    end
  end

  def show
    @organization = Organization.where(published: true).find(params[:id])
    respond_to do |format|
      format.html { render }
      format.json { render json: @organization.to_json }
    end
  end

  def edit
    @organization = Organization.find params[:id]
    if current_user.admin == false && @organization.user_id != current_user.id
      redirect_to organizations_path
    end
  end

  def update
    @organization = Organization.find params[:id]
    if current_user.admin == false && @organization.user_id != current_user.id
      redirect_to organizations_path
    end

    if @organization.update organization_params
      redirect_to organizations_path
    else
      render :edit
    end
  end

  def destroy
    @organization = Organization.find params[:id]
    if current_user.admin == false && @organization.user_id != current_user.id
      redirect_to organizations_path
    end

    @organization.destroy
    respond_to do |format|
      format.html { redirect_to organizations_path }
      format.js { render :destroy_success }
    end
  end

  def logo
    content = @organization.logo.read
    if stale?(etag: content, last_modified: @organization.updated_at.utc, public: true)
      send_data content, type: @organization.logo.file.content_type, disposition: "inline"
      expires_in 0, public: true
    end
  end

  private

  def organization_params
    params.require(:organization).permit([:name, :address, :logo,
                                         :overview, :employee_count,
                                         :tech_team_size, :website,
                                         :twitter, :published, {tech_stack_ids: []}, {images: []}])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :user_params, only: [:edit, :update, :destroy]
  before_action :authenticate_admin!, only: [:index]

  def index
    @users = User.all
    @pendings = PendingRequest.all
  end


  def new
    @user = User.new
  end

  def create
    @user = User.new(params.require(:user).permit([:first_name, :last_name, :email, :password, :password_confirmation]))

    if @user.save
      sign_in(@user)
      redirect_to root_path, notice: "Account Created!"
    else
      render :new, notice: "Account not created"
    end
  end

  def edit
  end

  def update
    if @user.update(params.require(:user).permit([:first_name, :last_name, :email, :password, :password_confirmation]))
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to root_path
  end

  private

  def user_params
    @user = User.find params[:id]
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper

  def event_objects
    url = "/HackerNestVan/events?photo-host=public&page=20&sig_id=204710864&sig=bd79ac9a7272dfe2a5a40a8a956b27ea0e1fdb85"

    conn = Faraday.new(url: 'https://api.meetup.com') do |faraday|
      faraday.request  :url_encoded             # form-encode POST params
      faraday.response :logger                  # log requests to STDOUT
      faraday.adapter  Faraday.default_adapter  # make requests with Net::HTTP
    end

    ## GET ##

    response = conn.get url     # GET http://sushi.com/nigiri/sake.json
    total_events = JSON.parse(response.body)

    puts total_events
    # method returns an array of JSON parsed events
  end

  def create_event_objects
    event_objects.each do |event|
      Event.create(title: event.name, url: event.link, description: event.description, group_name: event.group.name, time: event.time)
    end
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/meetups_helper.rb
module MeetupsHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tech_stacks_helper.rb
module TechStacksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/organizations/_form.html.erb
<%= simple_form_for @organization, html: { multipart: true, role: "form" } do |f| %>
  <%= f.input :name, wrapper_html: {class: "form-group"}, input_html: {class: "form-control"} %>
  <%= f.input :address, wrapper_html: {class: "form-group"}, input_html: {class: "form-control"}  %>
  <%= f.input :overview, label: "Overview", wrapper_html: {class: "form-group"}, input_html: {class: "form-control"} %>
  <%= f.input :employee_count, wrapper_html: {class: "form-group"}, input_html: {class: "form-control"}  %>
  <%= f.input :tech_team_size, wrapper_html: {class: "form-group"}, input_html: {class: "form-control"}  %>
  <%= f.input :website, wrapper_html: {class: "form-group"}, input_html: {class: "form-control"}  %>
  <%= f.input :twitter, wrapper_html: {class: "form-group"}, input_html: {class: "form-control"}  %>
  <% if current_user && current_user.admin %>
    <%= f.input :published  %>
  <% end %>
  <%= f.label :logo %><%= f.file_field :logo %>
  <%= f.association :tech_stacks, as: :check_boxes %>
  <%= f.file_field :images, multiple: true %>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/organizations/_image_carousel.html.erb
<div id="orgCarousel" class="carousel slide" data-ride="carousel">

  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
  </ol>

  <div class="carousel-inner" role="listbox">
    <div class="item active">
      <%= image_tag @organization.images[0].url(:large) %>
    </div>

    <% @organization.images.each_with_index do |i, index| %>
      <div class="item">
        <%= image_tag i.url(:large) %>
      </div>
    <% end %>
  </div>
  <a class="left carousel-control" href="#orgCarousel" role="button" data-slide="prev">
    <span class="icon-prev" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#orgCarousel" role="button" data-slide="next">
    <span class="icon-next" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>

</div>

app/views/organizations/_listing.html.erb
<% @organizations.each do |organization| %>
  <div class="row">

    <div class="col-md-2">
      <div class="col-md-5">
        <%= image_tag organization.logo.url(:thumb) %>
      </div>

      <div class="col-md-6">
        <div class="organization-elem" data_id="<%= organization.id %>">
          <%= link_to organization.name, organization_path(organization) %>
          <p><%= organization.employee_count %> employees</p>
        </div>
      </div>

    </div>

  </div>

<% end %>

app/views/organizations/_map.html.erb
<div id="map"></div>

app/views/organizations/destroy_success.js.erb
$("#<%= dom_id(@organization) %>").fadeOut(1000, function(){
  $(this).remove();
});

app/views/organizations/edit.html.erb
<h1>Edit Organization</h1>

<%= render "form" %>

app/views/organizations/home.html.erb
<!-- Map -->
<div id="large_map">
  <%= render "/organizations/map" %>
</div>

<!-- Search Bar -->
<div id="org-search-bar form-group">
  <%= form_tag organizations_path, method: 'get', remote:true do %>
    <%= text_field_tag :search, params[:search], id: "org-search-text", class: "form-control empty", placeholder:"Search" %>
  <% end %>
</div>
<br />

<!-- Tech Stacks -->
<div id="org-filter">
  <select id="tech-stacks" class="form-control">
    <option>      Tech Stack    </option>
      <% @techstacks.each_with_index do |stack, index| %>
        <option value=<%= index %>> <%= stack.name %>    </option>
      <% end  %>
  </select>
</div>

<!-- Team Size -->
<div id="org-filter">
  <select id="team-size" class="form-control ">
    <option value="0">      Team Size    </option>
    <option value="1">      Under 250    </option>
    <option value="2">      251 - 500    </option>
    <option value="3">      Above 500    </option>
  </select>
</div>
<br />
<br />

<!-- List of Organization -->
<div id="organizations_list" >
  <%= render "/organizations/listing" %>
</div>

<!-- Search Bar JQuery -->
<script>
$('#org-search-text').on('keyup', function() {
    var input = $(this);
    if(input.val().length === 0) {
        input.addClass('empty');
    } else {
        input.removeClass('empty');
    }
});
</script>

<!-- Script PseudoCode -->
<script>
// UL is filtered by the selection for Tech Stack and Team Size
// Depending on what is selected, show the listings that match
// Otherwise, show all
// Search only targets those companies that are shown
// var arg = [];

// enable search

// var searchTest = function (arg){
  // Takes input from the search box
  // var inputString = $("input#search").val();
  // Dynamic Search using RegExp --> Change for dropdown
  // var re = new RegExp(inputString, "i");
  // If the input consists of the input return true
//   if (re.test(arg.name)) {
//     return true;
//   }
//   else {
//     return false;
//   }
// }
//
// var filterOrganizations = function (){
//   return orgs.filter(searchTest);
  // Return an array of all the searchTest input
// }
</script>

<script async defer src="https://maps.googleapis.com/maps/api/js?callback=initMap">
</script>

app/views/organizations/index.html.erb
<h1>All Organizations</h1>

<div>
  <%= link_to "Add", new_organization_path %>
</div>

<div class="table-responsive">
  <table class="table">
    <thead>
      <tr>
        <th>Organization</th>
        <th>Published</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      <% @organizations.each do |org| %>
      <tr id="<%= dom_id(org) %>">
        <td><%= org.name %></td>
        <td><%= org.published ? "Yes" : "No" %></td>
        <td>
          <%= link_to "Show", organization_path(org) %>

            <% if current_user && (current_user.admin || org.user_id == current_user.id) %>
              <%= link_to "Edit", edit_organization_path(org)%>

              <%= link_to "Remove", organization_path(org),
                                data: {confirm: "Are you sure?"},
                                method: :delete,
                                remote: true %>

            <% end %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/organizations/new.html.erb
<h1>Organization</h1>

<%= render "form" %>

app/views/organizations/show.html.erb
<div id="organization-details" data_id="<%= @organization.id %>">

  <div class="row">

    <div class="col-md-3 col-md-offset-1 text-center">
      <%= image_tag @organization.logo.url %>

      <table class="table">
        <tbody>
          <tr>
            <td><b>Team Size</b></td>
            <td><%= @organization.employee_count %></td>
          </tr>
          <tr>
            <td><b>Tech Team</b></td>
            <td><%= @organization.tech_team_size %></td>
          </tr>
          <tr>
            <td><b>Tech Stack</b></td>
            <td>
              <% @organization.tech_stacks.each do |tech| %>
                <span>
                  <%= tech.name %>
                </span>
              <% end %>
            </td>
          </tr>
        </tbody>
      </table>

    </div>

    <!-- <div class="small_map">
      <%= render "/organizations/map" %>
    </div> -->

    <div class="col-md-6 org-info">
      <h1><%= link_to @organization.name, "http://#{@organization.website}" %></h1>

      <% if @organization.images.any? %>
        <%= render "/organizations/image_carousel" %>
      <% end %>

      <p><%= @organization.overview %></p>

    </div>

  </div>
  <div style="display: inline">
    Placeholder for map
  </div>

  <div class="container col-md-6">
    <a class="twitter-timeline" href="https://twitter.com/<%= @organization.twitter %>" >Tweets by <%= @organization.name %></a> <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
  </div>


  <div><%= link_to "Claim this organization", new_claim_organization_path({organization: @organization}) %></div>



</div>

<!-- <script async defer
src="https://maps.googleapis.com/maps/api/js?callback=initMap">
</script> -->