config/routes.rb
Rails.application.routes.draw do

  root "organizations#home"

  resources :tech_stacks, only: [:create, :new, :destroy]

  resources :organizations do
    get :logo, on: :member

    collection do
      get :home
    end
  end

  resources :claim_organizations

  get '/about' => 'home#about'

  resources :events

  resources :meetups, only: [:create, :new, :destroy]

  resources :users

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

  resources :news_searches
  
  resources :news, only: [:index]

  get "admin/users" => "admin#users"

end

app/models/event.rb
class Event < ActiveRecord::Base # :nodoc:
  belongs_to :meetup

  validates :title, uniqueness: { scope: :time }

  def start_time
    self.time
  end
end

app/models/meetup.rb
class Meetup < ActiveRecord::Base
  has_many :events, dependent: :destroy

  validates :title, presence: true, uniqueness: { message: "This Meetup is already in your list." }

  def total_events
    conn = Faraday.new(url: 'https://api.meetup.com') do |faraday|
      faraday.request  :url_encoded             # form-encode POST params
      faraday.response :logger                  # log requests to STDOUT
      faraday.adapter  Faraday.default_adapter  # make requests with Net::HTTP
    end

    response = conn.get url
    JSON.parse(response.body)
  end

  def seed_events(range)
    total_events.each do |event|
      event_time = event["time"]/1000

      if Time.at(event_time) < range.to_time
        Event.create(title: event["name"], url: event["link"], description: event["description"], group_name: event["group"]["name"], time: Time.at(event_time).localtime, meetup_id: id)
      end
    end
  end
end

app/models/news_search.rb
class NewsSearch < ActiveRecord::Base
end

app/models/organization.rb
class Organization < ActiveRecord::Base
  require 'carrierwave/orm/activerecord'

  mount_uploaders :images, ImageUploader

  has_many :tech_taggings, dependent: :destroy
  has_many :tech_stacks, through: :tech_taggings

  belongs_to :user

  has_many :pending_requests
  has_many :pending_mangers, through: :pending_requests, source: :user

  mount_uploader :logo, LogoUploader
end

app/models/pending_request.rb
class PendingRequest < ActiveRecord::Base
  belongs_to :user
  belongs_to :organization
end

app/models/tech_stack.rb
class TechStack < ActiveRecord::Base
  has_many :tech_taggings, dependent: :destroy
  has_many :tagged_organizations, through: :tech_taggings, source: :organization

  validates :name, presence: true, uniqueness: { message: "This technology already exists" }
end

app/models/tech_tagging.rb
class TechTagging < ActiveRecord::Base
  belongs_to :organization
  belongs_to :tech_stack
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  belongs_to :organization

  has_many :pending_requests
  has_many :pending_organization, through: :pending_requests, source: :organization

  validates :first_name, presence: true

  validates :last_name, presence: true

  VALID_EMAIL_REGEX = /\A([\w+\-]\.?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :email, uniqueness: true, presence: true, format: VALID_EMAIL_REGEX
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def about
  end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  OpenSSL::SSL::VERIFY_PEER = OpenSSL::SSL::VERIFY_NONE

  def index
    string_search_terms
    if @terms
      page = params[:page] || 1
      @news = GoogleCustomSearchApi.search(@terms, page: page)
    end
  end

  def string_search_terms
    @terms = ""
    NewsSearch.all.each do |term|
      @terms += " #{term.search_term}"
    end
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper

  def event_objects
    url = "/HackerNestVan/events?photo-host=public&page=20&sig_id=204710864&sig=bd79ac9a7272dfe2a5a40a8a956b27ea0e1fdb85"

    conn = Faraday.new(url: 'https://api.meetup.com') do |faraday|
      faraday.request  :url_encoded             # form-encode POST params
      faraday.response :logger                  # log requests to STDOUT
      faraday.adapter  Faraday.default_adapter  # make requests with Net::HTTP
    end

    ## GET ##

    response = conn.get url     # GET http://sushi.com/nigiri/sake.json
    total_events = JSON.parse(response.body)

    puts total_events
    # method returns an array of JSON parsed events
  end

  def create_event_objects
    event_objects.each do |event|
      Event.create(title: event.name, url: event.link, description: event.description, group_name: event.group.name, time: event.time)
    end
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/meetups_helper.rb
module MeetupsHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tech_stacks_helper.rb
module TechStacksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Vantech</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Vancouver Tech Hub", root_path, class: "navbar-brand" %>
      <!-- <a class="navbar-brand">Vancouver Tech Hub</a> -->
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Directory", organizations_path %><span class="sr-only">(current)</span></li>
        <li><%= link_to "Events", events_path %></li>
        <li><%= link_to "News", news_index_path %></li>
        <li><%= link_to "About", about_path %></li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <% if current_user.admin %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Admin Actions <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><%= link_to "All Users", users_path %></li>
                  <li><%= link_to "Add Company", new_organization_path %></li>
                  <li><%= link_to "Add Technology", new_tech_stack_path %></li>
                  <li><%= link_to "Add Meetup to Events", new_meetup_path %></li>
                  <li><%= link_to "Add News", news_searches_path %></li>
                </ul>
              </li>
          <% end %>
          <li><a href="#">Hello, <%= current_user.first_name %></a></li>
          <li><%= link_to "Log Out", sessions_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign In", new_session_path %></li>
          <li class="active"><%= link_to "Sign Up", new_user_path %><span class="sr-only">(current)</span></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

<div class="container">
  <% if notice || alert %>
    <hr>
      <%= notice || alert %>
    <hr>
  <% end %>

  <%= yield %>
</div>

<nav class="navbar navbar-default navbar-fixed-bottom">
  <div class="container-footer">
    <span>&#169; 2016</span>
    <p>Built and maintained by students from <a href="http://www.codecore.ca">CodeCore</a></p>
  </div>
</nav>

</body>

</html>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <%= link_to "Previous", calendar.url_for_previous_view %>
  <%= I18n.t("date.month_names")[start_date.month] %> <%= start_date.year %>
  <%= link_to "Next", calendar.url_for_next_view %>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= I18n.t("date.abbr_day_names")[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml do %>
                  <% block.call day, sorted_events.fetch(day, []) %>
                <% end %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <%= link_to "Previous", calendar.url_for_previous_view %>
  <%= I18n.t("date.month_names")[start_date.month] %> <%= start_date.year %>
  <%= link_to "Next", calendar.url_for_next_view %>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= I18n.t("date.abbr_day_names")[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml do %>
                  <% block.call day.strftime("%d"), sorted_events.fetch(day, []) %>
                <% end %>
              <% else %>
                <% block.call day.strftime("%d"), sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <%= link_to "Previous", calendar.url_for_previous_view %>
  Week <%= start_date.strftime("%U").to_i %>
  <%= link_to "Next", calendar.url_for_next_view %>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= I18n.t("date.abbr_day_names")[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml do %>
                  <% block.call day, sorted_events.fetch(day, []) %>
                <% end %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>